title: 'hrpr.uk'

header_pages:
  - index.md
  - about.md

style: light 

footer: 'follow <a href="https://twitter.com/hrpr">@hrpr</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
